$(function(){
   $('.li-guru').click(function(){
      $('.guru').css({
         display:'block' 
      });
       $('.siswa').css({
         display:'none' 
      });
       $('.nilai').css({
         display:'none' 
      });
       $('.user').css({
         display:'none' 
      });
       $('.jadwal').css({
         display:'none' 
      });
       $('.pelajaran').css({
         display:'none' 
      });
       $('.input').css({
         display:'none' 
      });
   });
    $('.li-siswa').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'none' 
      });
        $('.user').css({
         display:'none' 
      });
        $('.jadwal').css({
         display:'none' 
      });
       $('.siswa').css({
         display:'block' 
      });
        $('.pelajaran').css({
         display:'none' 
      });
        $('.input').css({
         display:'none' 
      });
   });
    $('.li-nilai').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'block' 
      });
       $('.siswa').css({
         display:'none' 
      });
        $('.user').css({
         display:'none' 
      });
        $('.jadwal').css({
         display:'none' 
      });
        $('.pelajaran').css({
         display:'none' 
      });
        $('.input').css({
         display:'none' 
      });
   });
    $('.li-jadwal').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'none' 
      });
       $('.siswa').css({
         display:'none' 
      });
        $('.user').css({
         display:'none' 
      });
        $('.jadwal').css({
         display:'block' 
      });
        $('.pelajaran').css({
         display:'none' 
      });
        $('.input').css({
         display:'none' 
      });
   });
    $('.li-user').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'none' 
      });
       $('.siswa').css({
         display:'none' 
      });
        $('.user').css({
         display:'block' 
      });
        $('.jadwal').css({
         display:'none' 
      });
        $('.pelajaran').css({
         display:'none' 
      });
        $('.input').css({
         display:'none' 
      });
   });
    $('.li-mapel').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'none' 
      });
       $('.siswa').css({
         display:'none' 
      });
        $('.user').css({
         display:'none' 
      });
        $('.jadwal').css({
         display:'none' 
      });
        $('.input').css({
         display:'none' 
      });
        $('.pelajaran').css({
         display:'block' 
      });
   });
    $('.li-input').click(function(){
      $('.guru').css({
         display:'none' 
      });
        $('.nilai').css({
         display:'none' 
      });
       $('.siswa').css({
         display:'none' 
      });
        $('.user').css({
         display:'none' 
      });
        $('.jadwal').css({
         display:'none' 
      });
        $('.pelajaran').css({
         display:'none' 
      });
        $('.input').css({
         display:'block' 
      });
   });
});